### ISSUE TITLE
Replacing ECCurve.py with the ECDSA implementation from cryptography

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python-core#21]
@ixje is thinking about replacing ECCurve.py with the ECDSA implementation from cryptography.

Input from @localhuman: "If I was going to replace the ECDSA implementation, I would do it in neo-python first so that I can verify it works with all the various signatures throughout the application."

**Comment by ixje** [comment]
so I've been trying different solutions for a couple of hours and here's my findings thus far.

[cryptography](https://github.com/pyca/cryptography) package
* Not the most straight forward, but looked promising. It did not support compressed point encoding, but with a little utility function I was able to solve that. 
* I can generate ECPoint/key data that equals the `neo-python` implementation, 👍 .
* I can sign/verify with their build in methods, but the signature output does equal that of the `neo-python` implementation. Signature length differs and cannot be configured. I can workaround this by just using the existing `Crypto.Sign()` and `Crypto.VerifySignature()` helper methods instead.
* It's still missing a method to load a public key from raw data. It currently only supports PEM/DER formats 👎 

[fastecdsa](https://github.com/AntonKueltz/fastecdsa) package
* Does not support 'secp256r1` out of the box, but has support for custom curves.
* I quickly added the curve but outputs didn't match. It's missing methods for validating if the points are on the curve as well as no easy ECPoint loading from raw data. I decided to not spend more time on it.

[python-ecdsa](https://github.com/warner/python-ecdsa) package
* Does not support `secp256r1` out of the box, also has no direct support for custom curves. Would require patching to support it (doesn't look difficult).
* There seem to be utility functions to initialise keys `from_string` so that's positive from a raw data loading (aka deserialisation) perspective.
* it also supports point validation and deterministic signing 👍
* I would have to try out the curve patching to see if it would be suitable.

If the latter doesn't work then I think it's not worth the effort any longer in trying to find a replacement. We could instead just ignore the `ECCurve.py` from the coverage as it's working and I doubt we'll have to replace it anytime soon. By that time existing package might have better support.

**Comment by metachris** [comment]
* Thanks for your research and documentation! 👍 
* Weird that `cryptography` wouldn't support loading a key from raw data.
* What I don't like about the `python-ecdsa` package is that there is basically [no development activity](https://github.com/warner/python-ecdsa/graphs/contributors). Makes me think it would probably not be worth it spending much time in making it work.
* Agree with you on your conclusion.
* If we just keep `ECCurve.py` then we should link to this discussion thread in the documentation at the top of the Python file.
